name: Sandbox

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: cat /etc/os-release
      - run: grep -q 'Name="Ubuntu"' /etc/os-release
      - run: pwd
      - run: whoami
      - run: env
      - run: which go
      - run: go version
      - run: wget https://go.dev/dl/go1.21.6.linux-amd64.tar.gz
      # - run: sudo rm -f /usr/bin/go
      - run: sudo tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
      - run: sudo ln -sf /usr/local/go/bin/go /usr/bin/go
      - run: go version
