name: Sandbox

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: which go
      - run: go version
      - run: go install golang.org/dl/go1.20.11@latest
      - run: go1.20.11 download
      - run: go1.20.11 version
