name: Sandbox

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: which go
      - run: go version
      - run: |
         wget https://go.dev/dl/go1.21.6.linux-amd64.tar.gz
         rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
      - run: go version
      

