name: Sandbox

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: whoami
      - run: env
      - run: which go
      - run: go version
      - run: wget https://go.dev/dl/go1.21.6.linux-amd64.tar.gz
      # - run: rm -rf /usr/local/go
      - run: rm -f /usr/bin/go
      - run: sudo tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
      - run: export PATH=$PATH:/usr/local/go/bin
      - run: source $HOME/.profile
      - run: go version
